### ISSUE TITLE
How to get your trained bilingual dictionary by code

### ISSUE THREAD

**Issue by Cupid777** [kakaobrain/word2word#13]
How to get your trained bilingual dictionary by code？

**Comment by Vuizur** [comment]
I had the same problem, I wrote a function to export the dictionary to a tabfile dictionary in a [fork](https://github.com/Vuizur/word2word). So you can use it like this:
```
w2w = Word2word("cs", "de")
w2w.export_to_tabfile("cs-de.txt")
```
